add a blog of dsproxy-deadlock
seata/seata.github.io pull request #303
Opened 2021-03-13 12:34 UTC by spilledyear

介绍了一个线上问题，因ConcurrentHashMap的Bug而导致的Seata动态数据源代理死锁

2021-03-13 14:47 UTC, a364176773 requested changes

2021-03-13 14:47 UTC, a364176773 commented on blog/zh-cn/seata-dsproxy-deadlock.md
> +1. seata版本：1.4.0
建议把会触发此问题的几个版本号稍微列一列.列出已知即可,太古老版本可不列

2021-03-14 09:06 UTC, spilledyear commented on blog/zh-cn/seata-dsproxy-deadlock.md
> +1. seata版本：1.4.0
ok

2021-03-14 09:14 UTC, a364176773 approved these changes
LGTM

2021-03-14 09:14 UTC, merged