补充详细的docker-compose部署seata-server方式
seata/seata.github.io pull request #391
Opened 2021-12-05 15:34 UTC by zw201913

1.docker-compose【单机模式】、【nacos注册中心db模式】、【多实例高可用模式】等多种部署seata-server方式
2.补充db模式下相应的建表sql语句
3.补充注册中心配置示例、配置中心配置示例

2021-12-06 08:42 UTC, tanzzj commented on docs/zh-cn/ops/deploy-by-docker-compose.md
> +service.vgroupMapping.my_test_tx_group=default
1.5.0之后，默认事务分组改成了default_tx_group。可以备注一下

2021-12-06 09:15 UTC, zw201913 commented on docs/zh-cn/ops/deploy-by-docker-compose.md
> +service.vgroupMapping.my_test_tx_group=default
好的，后续我再根据实际版本进行对应调整

2021-12-06 09:47 UTC, zw201913 commented on docs/zh-cn/ops/deploy-by-docker-compose.md
> +service.vgroupMapping.my_test_tx_group=default
我刚刚已经补充了关于1.5.0版本后的默认事务分组名称的变化。

2021-12-06 15:09 UTC, tanzzj commented on docs/zh-cn/ops/deploy-by-docker-compose.md
> +-- the table to store GlobalSession data
表结构建议路由到主仓库的resources地址，否则后续更新了表结构，文章也要相应改，可能导致更新不及时的问题

2021-12-06 15:10 UTC, tanzzj commented on docs/zh-cn/ops/deploy-by-docker-compose.md
> +## 配置示例
其实配置事例demo和官网有很多，这里这样放感觉挺冗余？

2021-12-07 06:45 UTC, zw201913 commented on docs/zh-cn/ops/deploy-by-docker-compose.md
> +## 配置示例
主要有两点原因：
1.方便开发者直接取，不用各种跳转找建表语句。另在正文中有给到resources的链接。
2.在开发人员无法访问github的情况下，可直接用文中的建表语句。

2021-12-13 16:45 UTC, tanzzj requested changes

2021-12-13 16:45 UTC, tanzzj commented on docs/zh-cn/ops/deploy-by-docker-compose.md
> +#【如果nacos服务是docker运行的话，config.type需要指定为file模式，否则会报错】
这里跟nacos服务是不是docker运行没有什么直接关系吧？nacos是docker运行的情况下，跟seata使用什么config模式没直接关系

2021-12-13 16:45 UTC, tanzzj commented on docs/zh-cn/ops/deploy-by-docker-compose.md
> +    image: seataio/seata-server:1.4.2
这里其实最好就采用变量的形式去代替这个版本号，因为后续版本升级后，如果这个文章没有得到及时的变更，其实会误导刚接触的同学，最好就采用 ${latest-release-version}这样的变量（或者更好的变量）

2021-12-13 16:45 UTC, tanzzj commented on docs/zh-cn/ops/deploy-by-docker-compose.md
> +> 只要保持配置一致，seata服务可在一台机器上部署多实例，也可同时部署在多台不同的主机下面实现服务高可用。
这里可以延申给个事务分组与高可用的连接，提供给用户参考阅读，其他没什么问题了

2021-12-13 16:45 UTC, tanzzj commented on docs/zh-cn/ops/deploy-by-docker-compose.md
> +#【如果nacos服务是docker运行的话，config.type需要指定为file模式，否则会报错】
同理

2021-12-19 15:28 UTC, tanzzj approved these changes
LGTM

2021-12-20 01:50 UTC, lvekee commented on docs/zh-cn/ops/deploy-by-docker-compose.md
> +**（1）准备file.conf配置文件**
可以将config.type也修改为nacos，配置中心为file上边已经有介绍，这里可以展示nacos同时也作为配置中心的做法。

2021-12-20 01:50 UTC, lvekee commented on docs/zh-cn/ops/deploy-by-docker-compose.md
> +service.vgroupMapping.my_test_tx_group=default
事务分组的概念属于客户端配置，server不需要这个配置

2021-12-20 01:50 UTC, lvekee commented on docs/zh-cn/ops/deploy-by-docker-compose.md
> +service.vgroupMapping.my_test_tx_group=default
同上

2021-12-20 01:50 UTC, lvekee commented on docs/zh-cn/ops/deploy-by-docker-compose.md
> +service.vgroupMapping.my_test_tx_group=default
同上

2021-12-20 05:18 UTC, zw201913 commented on docs/zh-cn/ops/deploy-by-docker-compose.md
> +service.vgroupMapping.my_test_tx_group=default
已经调整了，确认一下

2021-12-20 05:18 UTC, zw201913 commented on docs/zh-cn/ops/deploy-by-docker-compose.md
> +service.vgroupMapping.my_test_tx_group=default
补充了对应的nacos配置中心相关的配置

2021-12-20 06:53 UTC, lvekee commented on docs/zh-cn/ops/deploy-by-docker-compose.md
> +**（2）准备nacos配置中心配置**
nacos配置中心，在1.4.2版本之后才支持一个dataId放所有的配置，这里是不是可以简单表述一下，具体可以参考nacos配置中心文档

2021-12-20 06:53 UTC, lvekee commented on docs/zh-cn/ops/deploy-by-docker-compose.md
> +
感觉高可用部署 不需要将配置文件等配置再写一遍，直接给出docker-compose.yaml这个配置即可，因为本文上半部分已经交过单机怎么部署了。

2021-12-23 14:40 UTC, caohdgege commented on docs/zh-cn/ops/deploy-by-docker-compose.md
> +> 可选, 指定seata-server的事务日志存储方式, 支持`db` ,`file`,redis(Seata-Server 1.3及以上版本支持), 默认是 `file`
redis -> `redis`

2021-12-23 15:13 UTC, tanzzj approved these changes
LGTM

2021-12-23 15:34 UTC, merged