完善了官网文档
seata/seata.github.io pull request #392
Opened 2021-12-14 06:14 UTC by zyplanke

完善了官网文档：
1、Seata介绍（增加了github中README.md中图，这么好的图不放在官网文档中，多可惜）
2、Seata事务分组：对说明解释进行了完善避免了歧义。 由于客户端无像服务端需要registry {}和config {}，所以将其删除。  纠正了“-fescar-service-group”等错误内容

2021-12-14 06:18 UTC, a364176773 requested changes

2021-12-14 06:18 UTC, a364176773 commented on docs/zh-cn/user/txgroup/transaction-group.md
> +seata.tx-service-group=my_test_tx_group ---------------> 事务分组定义（两种方式等价，二选一）
seata-all不支持application.properties的配置，只支持file.properties registy.properties或yml&conf，所以你这里应该是添加springboot的配置方式，而非删除spring的配置方式

2021-12-14 06:18 UTC, a364176773 commented on docs/zh-cn/user/txgroup/transaction-group.md
> +spring.cloud.alibaba.seata.tx-service-group=my_test_tx_group ---------------> 事务分组定义
2.2.1spring-cloud-starter-alibaba-seata后无需此配置，改为seata.tx-service-group

2021-12-14 06:42 UTC, zyplanke commented on docs/zh-cn/user/txgroup/transaction-group.md
> +seata.tx-service-group=my_test_tx_group ---------------> 事务分组定义（两种方式等价，二选一）
是的。不同的情况应该分别说明。

2021-12-14 06:48 UTC, zyplanke commented on docs/zh-cn/user/txgroup/transaction-group.md
> +spring.cloud.alibaba.seata.tx-service-group=my_test_tx_group ---------------> 事务分组定义
嗯。1.4.2版本下两者都可以生效。统一为seata.tx-service-group，这样seata的配置比较规整

2021-12-20 06:28 UTC, a364176773 approved these changes
LGTM

2021-12-20 06:35 UTC, Pinocchio2018 commented
hi，请把本pr的标题改为英文，合并后你的多个commit会squash成一个commit（自动使用你的pr标题）

2021-12-21 01:16 UTC, Pinocchio2018 commented on docs/zh-cn/user/txgroup/transaction-group.md
> +seata.tx-service-group=my_test_tx_group ---------------> 事务分组配置
我是这样想的，这里的Client端是不是再做下分块，会不会更好理解一些，像这样
#### Client端
registry.conf
```
registry {
  # file 、nacos 、eureka、redis、zk、consul、etcd3、sofa
  type = "file"                ---------------> 使用file作为注册中心
}
config {
  # file、nacos 、apollo、zk、consul、etcd3
  type = "file"                ---------------> 使用file作为配置中心
  file {
    name = "file.conf"         ---------------> 配置参数存储文件
  }
}
```
application.properties
```
seata.tx-service-group=my_test_tx_group ---------------> 事务分组配置
```
file.conf
```
service {
   vgroupMapping.my_test_tx_group = "default"
   default.grouplist = "127.0.0.1:8091"
}
```

2021-12-21 01:21 UTC, Pinocchio2018 commented on docs/zh-cn/user/txgroup/transaction-group.md
> +seata.registry.type=file
这里已经在介绍第二类注册中心了，我觉得这里的file不合适，会有些误导作用

2021-12-21 01:32 UTC, Pinocchio2018 commented on docs/zh-cn/user/txgroup/transaction-group.md
> +seata.service.grouplist.cluster_beijing=127.0.0.1:8091
噢！我看明白了，这里说的是这2个参数不是file的时候不需要。改成这样会不会好些
```
# seata.registry.type=nacos或其他类型时（微服务客户端和seata-server服务端应同时指定为nacos），则无需以下2个参数
# seata.registry.type=file
# seata.service.grouplist.cluster_beijing=127.0.0.1:8091
```

2021-12-21 15:37 UTC, zyplanke commented on docs/zh-cn/user/txgroup/transaction-group.md
> +seata.tx-service-group=my_test_tx_group ---------------> 事务分组配置
已经拆分描述。

2021-12-21 15:38 UTC, zyplanke commented on docs/zh-cn/user/txgroup/transaction-group.md
> +seata.service.grouplist.cluster_beijing=127.0.0.1:8091
该处描述文字已经调整（另并按实际补充了seata-server使用nacos的参数）

2021-12-22 01:11 UTC, Pinocchio2018 commented on docs/zh-cn/user/txgroup/transaction-group.md
>  file.conf:
早上好。代码块里的`file.conf`多余了，上面这行写过了

2021-12-22 02:54 UTC, zyplanke commented on docs/zh-cn/user/txgroup/transaction-group.md
>  file.conf:
已经调整

2021-12-23 02:47 UTC, lvekee approved these changes
LGTM

2021-12-23 02:55 UTC, Pinocchio2018 commented on docs/zh-cn/user/txgroup/transaction-group.md
> +>> 另外：若Client不通过Nacos获取seata-server服务信息，而是直接指定seata-server服务端节点的IP和端口信息，则可将以上application.properties中涉及nacos几个配置改为如两个配置：
这里用一个 > 符号就够了~
![image](https://user-images.githubusercontent.com/24909409/147181031-40e58719-c7a0-45d3-8544-77ec694f1d3f.png)

2021-12-23 02:57 UTC, Pinocchio2018 commented on docs/zh-cn/user/txgroup/transaction-group.md
> +seata.service.vgroup-mapping.my_test_tx_group=cluster_beijing  ---------------> 指定事务分组至集群映射关系（等号右侧的集群名需要与Seata服务端配置的cluster保持一致）
这块我可能说的不太对。
像`seata.service.vgroup-mapping.my_test_tx_group=cluster_beijing`这个，应该是放在配置中心里的。而不是放在application.properties里的。我担心放在这里会引起用户误解

2021-12-23 03:05 UTC, Pinocchio2018 commented on docs/zh-cn/user/txgroup/transaction-group.md
> +seata.registry.nacos.application=seata-server     ---------------> Seata服务名（应与seata-server实际注册的服务名一致）
我觉得这里也可以做下区分，像这样
application.properties
```
seata.registry.type=nacos      ---------------> 使用nacos作为注册中心
seata.registry.nacos.server-addr=nacos      --------------->注册中心IP:端口
seata.registry.nacos.application=yourApplication     ---------------> Seata服务名（应与seata-server实际注册的服务名一致）
```

配置中心配置项
```
seata.service.vgroup-mapping.yourApplication=cluster_beijing ---------------> 指定事务分组至集群映射关系（等号右侧的集群名需要与Seata服务端配置的cluster保持一致）
```

（可能说的不对，只是提一提我的阅读完以后的看法）

2021-12-23 04:11 UTC, tanzzj commented on docs/zh-cn/user/txgroup/transaction-group.md
> +seata.service.vgroup-mapping.my_test_tx_group=cluster_beijing  ---------------> 指定事务分组至集群映射关系（等号右侧的集群名需要与Seata服务端配置的cluster保持一致）
1. spring.cloud.alibaba.seata 前缀的配置后续会移除, 保留seata开头的配置，我们不再建议用户直接使用sca的配置
2. tx-service-group 的默认值 my_test_tx_group 在1.5之后改成了default_tx_group, 可以备注下

2021-12-23 08:05 UTC, zyplanke commented on docs/zh-cn/user/txgroup/transaction-group.md
> +>> 另外：若Client不通过Nacos获取seata-server服务信息，而是直接指定seata-server服务端节点的IP和端口信息，则可将以上application.properties中涉及nacos几个配置改为如两个配置：
已经调整格式。

2021-12-23 08:06 UTC, zyplanke commented on docs/zh-cn/user/txgroup/transaction-group.md
> +seata.service.vgroup-mapping.my_test_tx_group=cluster_beijing  ---------------> 指定事务分组至集群映射关系（等号右侧的集群名需要与Seata服务端配置的cluster保持一致）
已经调整：
Added: 增加在v1.5之后seata.tx-service-group默认值为default_tx_group备注
Fiexed: 删除spring.cloud.alibaba.seata的配置项，修改个别文字和排版格式
Changed：调整Nacos配置中心脚本的说明段落

2021-12-23 08:41 UTC, lvekee commented on docs/zh-cn/user/txgroup/transaction-group.md
> +     - nacos/        推送至nacos的脚本
这里的目录是不是没写完整 漏掉了

2021-12-23 08:41 UTC, lvekee commented on docs/zh-cn/user/txgroup/transaction-group.md
> +     - zk/
同上

2021-12-23 08:50 UTC, zyplanke commented on docs/zh-cn/user/txgroup/transaction-group.md
> +seata.registry.nacos.application=seata-server     ---------------> Seata服务名（应与seata-server实际注册的服务名一致）
seata.service.vgroup-mapping，我理解它用于客户端从nacos获取服务列表时需要的cluster名（查找所属哪个cluster下的服务列表）， 与配置中心没有关系吧

2021-12-23 08:57 UTC, zyplanke commented on docs/zh-cn/user/txgroup/transaction-group.md
> +     - zk/
目录列全了。目录的中文说明后面没写。该节是介绍nacos，其他就点到为止没写中文。不过英文目录名已经一目了然，还写么？

2021-12-23 15:02 UTC, tanzzj approved these changes
LGTM

2021-12-23 15:37 UTC, merged